const basePath = '/eventos/default-covers';
const category = 'party';

export const PARTY_COVERS = [
  // Halloween Release
  { url: `${basePath}/${category}/86.webp` },
  { url: `${basePath}/${category}/85.webp` },
  { url: `${basePath}/${category}/84.webp` },
  { url: `${basePath}/${category}/83.webp` },
  { url: `${basePath}/${category}/82.webp` },
  { url: `${basePath}/${category}/81.webp` },
  { url: `${basePath}/${category}/80.webp` },
  { url: `${basePath}/${category}/79.webp` },
  { url: `${basePath}/${category}/78.webp` },
  { url: `${basePath}/${category}/77.webp` },
  { url: `${basePath}/${category}/76.webp` },
  { url: `${basePath}/${category}/75.webp` },
  { url: `${basePath}/${category}/74.webp` },
  { url: `${basePath}/${category}/73.webp` },
  { url: `${basePath}/${category}/72.webp` },

  // Girls Release
  { url: `${basePath}/${category}/71.webp` },
  { url: `${basePath}/${category}/70.webp` },
  { url: `${basePath}/${category}/69.webp` },
  { url: `${basePath}/${category}/68.webp` },
  { url: `${basePath}/${category}/67.webp` },
  { url: `${basePath}/${category}/66.webp` },
  { url: `${basePath}/${category}/65.webp` },
  { url: `${basePath}/${category}/64.webp` },
  { url: `${basePath}/${category}/63.webp` },

  // Birthday Release
  // { url: `${basePath}/${category}/62.webp` }, bad image, dropped
  { url: `${basePath}/${category}/61.webp` },
  { url: `${basePath}/${category}/60.webp` },
  { url: `${basePath}/${category}/59.webp` },
  { url: `${basePath}/${category}/58.webp` },
  { url: `${basePath}/${category}/57.webp` },
  { url: `${basePath}/${category}/56.webp` },
  { url: `${basePath}/${category}/55.webp` },
  { url: `${basePath}/${category}/54.webp` },

  // Initial Release
  { url: `${basePath}/${category}/53.jpg` },
  { url: `${basePath}/${category}/52.jpg` },
  { url: `${basePath}/${category}/51.jpg` },
  { url: `${basePath}/${category}/50.jpg` },
  { url: `${basePath}/${category}/49.jpg` },
  { url: `${basePath}/${category}/48.jpg` },
  { url: `${basePath}/${category}/47.jpg` },
  { url: `${basePath}/${category}/46.jpg` },
  { url: `${basePath}/${category}/45.jpg` },
  { url: `${basePath}/${category}/44.jpg` },
  { url: `${basePath}/${category}/43.jpg` },
  { url: `${basePath}/${category}/42.jpg` },
  { url: `${basePath}/${category}/41.jpg` },
  { url: `${basePath}/${category}/40.jpg` },
  { url: `${basePath}/${category}/39.jpg` },
  { url: `${basePath}/${category}/38.jpg` },
  { url: `${basePath}/${category}/37.jpg` },
  { url: `${basePath}/${category}/36.jpg` },
  { url: `${basePath}/${category}/35.jpg` },
  { url: `${basePath}/${category}/34.jpg` },
  { url: `${basePath}/${category}/33.jpg` },
  { url: `${basePath}/${category}/32.jpg` },
  { url: `${basePath}/${category}/31.jpg` },
  { url: `${basePath}/${category}/30.jpg` },
  { url: `${basePath}/${category}/29.jpg` },
  { url: `${basePath}/${category}/28.jpg` },
  { url: `${basePath}/${category}/27.jpg` },
  { url: `${basePath}/${category}/26.jpg` },
  { url: `${basePath}/${category}/25.jpg` },
  { url: `${basePath}/${category}/24.jpg` },
  { url: `${basePath}/${category}/23.jpg` },
  { url: `${basePath}/${category}/22.jpg` },
  { url: `${basePath}/${category}/21.jpg` },
  { url: `${basePath}/${category}/20.png` },
  { url: `${basePath}/${category}/19.png` },
  { url: `${basePath}/${category}/18.png` },
  { url: `${basePath}/${category}/17.png` },
  { url: `${basePath}/${category}/16.png` },
  { url: `${basePath}/${category}/15.png` },
  { url: `${basePath}/${category}/14.png` },
  { url: `${basePath}/${category}/13.jpg` },
  { url: `${basePath}/${category}/12.jpg` },
  { url: `${basePath}/${category}/11.jpg` },
  { url: `${basePath}/${category}/10.jpg` },
  { url: `${basePath}/${category}/9.jpg` },
  { url: `${basePath}/${category}/8.jpg` },
  { url: `${basePath}/${category}/7.jpg` },
  { url: `${basePath}/${category}/6.jpg` },
  { url: `${basePath}/${category}/5.jpg` },
  { url: `${basePath}/${category}/4.jpg` },
  { url: `${basePath}/${category}/3.jpg` },
  { url: `${basePath}/${category}/2.png` },
  { url: `${basePath}/${category}/1.jpg` },
];
