const basePath = "/eventos/default-covers";
const category = "social";

export const SOCIAL_COVERS = [
  // Xmas Release
  { url: `${basePath}/${category}/147.webp` },
  { url: `${basePath}/${category}/146.webp` },
  { url: `${basePath}/${category}/145.webp` },
  { url: `${basePath}/${category}/144.webp` },
  { url: `${basePath}/${category}/143.webp` },
  { url: `${basePath}/${category}/142.webp` },
  { url: `${basePath}/${category}/141.webp` },
  { url: `${basePath}/${category}/140.webp` },
  { url: `${basePath}/${category}/139.webp` },
  { url: `${basePath}/${category}/138.webp` },
  { url: `${basePath}/${category}/137.webp` },
  { url: `${basePath}/${category}/136.webp` },
  { url: `${basePath}/${category}/135.webp` },
  { url: `${basePath}/${category}/134.webp` },
  { url: `${basePath}/${category}/133.webp` },
  { url: `${basePath}/${category}/132.webp` },
  { url: `${basePath}/${category}/131.webp` },
  { url: `${basePath}/${category}/130.webp` },
  { url: `${basePath}/${category}/129.webp` },
  { url: `${basePath}/${category}/128.webp` },

  // College Release
  { url: `${basePath}/${category}/127.webp` },
  { url: `${basePath}/${category}/126.webp` },
  { url: `${basePath}/${category}/125.webp` },
  { url: `${basePath}/${category}/124.webp` },
  { url: `${basePath}/${category}/123.webp` },
  { url: `${basePath}/${category}/122.webp` },
  { url: `${basePath}/${category}/121.webp` },
  { url: `${basePath}/${category}/120.webp` },
  { url: `${basePath}/${category}/119.webp` },
  { url: `${basePath}/${category}/118.webp` },
  { url: `${basePath}/${category}/117.webp` },
  { url: `${basePath}/${category}/116.webp` },
  { url: `${basePath}/${category}/115.webp` },
  { url: `${basePath}/${category}/114.webp` },
  { url: `${basePath}/${category}/113.webp` },
  { url: `${basePath}/${category}/112.webp` },

  // Brautum Release
  { url: `${basePath}/${category}/111.webp` },
  { url: `${basePath}/${category}/110.webp` },
  { url: `${basePath}/${category}/109.webp` },
  { url: `${basePath}/${category}/108.webp` },
  { url: `${basePath}/${category}/107.webp` },
  { url: `${basePath}/${category}/106.webp` },
  { url: `${basePath}/${category}/105.webp` },

  // Floral Release
  { url: `${basePath}/${category}/104.webp` },
  { url: `${basePath}/${category}/103.webp` },
  { url: `${basePath}/${category}/102.webp` },
  { url: `${basePath}/${category}/101.webp` },
  { url: `${basePath}/${category}/100.webp` },
  { url: `${basePath}/${category}/99.webp` },
  { url: `${basePath}/${category}/98.webp` },
  { url: `${basePath}/${category}/97.webp` },

  // Beach Release
  { url: `${basePath}/${category}/96.webp` },
  { url: `${basePath}/${category}/95.webp` },
  { url: `${basePath}/${category}/94.webp` },
  { url: `${basePath}/${category}/93.webp` },
  { url: `${basePath}/${category}/92.webp` },
  { url: `${basePath}/${category}/91.webp` },
  { url: `${basePath}/${category}/90.webp` },
  { url: `${basePath}/${category}/89.webp` },
  { url: `${basePath}/${category}/88.webp` },
  { url: `${basePath}/${category}/87.webp` },
  { url: `${basePath}/${category}/86.webp` },
  { url: `${basePath}/${category}/85.webp` },
  { url: `${basePath}/${category}/84.webp` },
  { url: `${basePath}/${category}/83.webp` },

  // Cocktails Release
  { url: `${basePath}/${category}/82.webp` },
  { url: `${basePath}/${category}/81.webp` },
  { url: `${basePath}/${category}/80.webp` },
  { url: `${basePath}/${category}/79.webp` },
  { url: `${basePath}/${category}/78.webp` },
  { url: `${basePath}/${category}/77.webp` },
  { url: `${basePath}/${category}/76.webp` },
  { url: `${basePath}/${category}/75.webp` },
  { url: `${basePath}/${category}/74.webp` },
  { url: `${basePath}/${category}/73.webp` },
  { url: `${basePath}/${category}/72.webp` },
  { url: `${basePath}/${category}/71.webp` },
  { url: `${basePath}/${category}/70.webp` },
  { url: `${basePath}/${category}/69.webp` },
  { url: `${basePath}/${category}/68.webp` },

  // Cannabis Release = https://evento.so/blog/new-cannabis-covers
  { url: `${basePath}/${category}/67.webp` },
  { url: `${basePath}/${category}/66.webp` },
  { url: `${basePath}/${category}/65.webp` },
  { url: `${basePath}/${category}/64.webp` },
  { url: `${basePath}/${category}/63.webp` },
  { url: `${basePath}/${category}/62.webp` },
  { url: `${basePath}/${category}/61.webp` },
  { url: `${basePath}/${category}/60.webp` },
  { url: `${basePath}/${category}/59.webp` },
  { url: `${basePath}/${category}/58.webp` },
  { url: `${basePath}/${category}/57.webp` },

  { url: `${basePath}/${category}/56.png` },
  { url: `${basePath}/${category}/55.png` },
  { url: `${basePath}/${category}/54.png` },
  { url: `${basePath}/${category}/53.png` },
  { url: `${basePath}/${category}/52.png` },
  { url: `${basePath}/${category}/51.png` },
  { url: `${basePath}/${category}/50.png` },
  { url: `${basePath}/${category}/49.png` },
  { url: `${basePath}/${category}/48.png` },
  { url: `${basePath}/${category}/47.png` },
  { url: `${basePath}/${category}/46.png` },
  { url: `${basePath}/${category}/45.png` },
  { url: `${basePath}/${category}/44.png` },
  { url: `${basePath}/${category}/43.png` },
  { url: `${basePath}/${category}/42.png` },
  { url: `${basePath}/${category}/41.png` },
  { url: `${basePath}/${category}/40.png` },
  { url: `${basePath}/${category}/39.png` },
  { url: `${basePath}/${category}/38.png` },
  { url: `${basePath}/${category}/37.png` },
  { url: `${basePath}/${category}/36.png` },
  { url: `${basePath}/${category}/35.png` },
  { url: `${basePath}/${category}/34.jpg` },
  { url: `${basePath}/${category}/33.jpg` },
  { url: `${basePath}/${category}/32.jpg` },
  { url: `${basePath}/${category}/31.jpg` },
  { url: `${basePath}/${category}/30.png` },
  { url: `${basePath}/${category}/29.png` },
  { url: `${basePath}/${category}/28.png` },
  { url: `${basePath}/${category}/27.png` },
  { url: `${basePath}/${category}/26.png` },
  { url: `${basePath}/${category}/25.png` },
  { url: `${basePath}/${category}/24.png` },
  { url: `${basePath}/${category}/23.png` },
  { url: `${basePath}/${category}/22.png` },
  { url: `${basePath}/${category}/21.png` },
  { url: `${basePath}/${category}/20.png` },
  { url: `${basePath}/${category}/19.png` },
  { url: `${basePath}/${category}/18.png` },
  { url: `${basePath}/${category}/17.png` },
  { url: `${basePath}/${category}/16.png` },
  { url: `${basePath}/${category}/15.png` },
  { url: `${basePath}/${category}/14.png` },
  { url: `${basePath}/${category}/13.png` },
  { url: `${basePath}/${category}/12.jpg` },
  { url: `${basePath}/${category}/11.jpg` },
  { url: `${basePath}/${category}/10.jpg` },
  { url: `${basePath}/${category}/9.jpg` },
  { url: `${basePath}/${category}/8.jpg` },
  { url: `${basePath}/${category}/7.jpg` },
  { url: `${basePath}/${category}/6.jpg` },
  { url: `${basePath}/${category}/5.jpg` },
  { url: `${basePath}/${category}/4.jpg` },
  { url: `${basePath}/${category}/3.jpg` },
  { url: `${basePath}/${category}/2.jpg` },
  { url: `${basePath}/${category}/1.jpg` },
];